version: '3'

services:
  db:
    image: mariadb
    command: --character_set_server=utf8 --collation_server=utf8_general_ci
    restart: always
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend

  app:
    image: wallabag/wallabag:2.4.2
    restart: always
    volumes:
      - images:/var/www/wallabag/web/assets/images
    depends_on:
      - db
    networks:
      - frontend
      - backend

volumes:
  db:
  images:

networks:
  frontend:
    external:
      name: proxy_frontend
  backend:
